#%RAML 0.8
title: Users API
version: 1
baseUri: https://express-app-returning-zip.herokuapp.com
mediaType: application/json
schemas:
- Order: |
    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "number"
          },
          "name" : {
            "type" : "string"
          }
        }
      }
/users:
  displayName: retrieve all orders
  /{userId}/order:
    displayName: access user's orders
    get:      
      description: retrieve a user's picture      
      queryParameters:
        orderId:
          description: Order Id
          type: integer
          required: true
          example: 1
      responses:
        200:
          body:
            application/json:
                schema: Order